### ISSUE TITLE
Chatrooms : Received messages only update when sending a message

### ISSUE THREAD

**Issue by Scelewyn** [znichola/ft_transcendence#100]

**Comment by znichola** [comment]
This is something I tried to work on, and the best i could do was get reactQuery to refetch/insert the new message when the user is focused on the window, so when you test make sure you actually click the window as you switch between the two, maybe there is a fix for it but it could take a few hours to find.

**Comment by znichola** [comment]
this is solved, one way or another, we're updating out the wazooo
