### ISSUE TITLE
Special layout when message is blocked

### ISSUE THREAD

**Issue by sophiakoulen** [znichola/ft_transcendence#124]
If the `isBlocked` flag is true, maybe put it in italic or something.
That way, you can distinguish between someone who's actually blocked and a troll
<img width="2560" alt="Screen Shot 2023-10-30 at 2 44 32 PM" src="https://github.com/znichola/ft_transcendence/assets/100098656/5f60d7e8-585d-4399-9a2e-e60216fce872">

**Comment by znichola** [comment]
thank you for the feedback, but it's not is the future roadmap.
