### ISSUE TITLE
Special Pong

### ISSUE THREAD

**Issue by rnbw8** [znichola/ft_transcendence#17]
a ball has a x% chance to split into 2 (smaller?) balls every time it crosses the middle field. game reset only when all balls disappear (= when scored). 
if normal won with 5 points, then special won with 10? 15? 20?

**Comment by Scelewyn** [comment]
Ball splitting could send a ball to each player to prevent auto-scoring if you get unlucky RNG

**Comment by znichola** [comment]
yeah, that could be a good way to get it more balanced
