### ISSUE TITLE
QRCode generation returns file data instead of image

### ISSUE THREAD

**Issue by Scelewyn** [znichola/ft_transcendence#37]
When generating a QR code for the user to scan, the generated QR code is returned as text (this text can be saved to a file to create the working QR Code)
Do you have any ways to use it in React to display the image from its data ? I cannot use the same ReadStream as I did for the user avatar because the QRCode is not locally saved

**Comment by znichola** [comment]
hmm, I'm not sure, I did a quick search online and maybe it's possible? idk, would be simpler to just send a string right?

**Comment by Scelewyn** [comment]
I can send you the string yes, but then you need to make an image out of it
When trying it in Hoppscotch I get the string, but in Swagger it shows the QRCode correctly, so we should be able to make it work

**Comment by Scelewyn** [comment]
This issue was handled, QRcode is now displayed properly !
