### ISSUE TITLE
can't add new users to chatroom - TODO: change rules for adding users

### ISSUE THREAD

**Issue by znichola** [znichola/ft_transcendence#58]
when trying to add a users while being the admin, maybe the api has changed? 
this is needed for when you have a private room and want to add people, the same add users browser is present for public chatrooms also, and it's where I'm getting the error.

```
{
  message: "You are not allowed to add users other than yourself in this chatroom",
  error: "Forbidden",
  statusCode: 403,
}
```
![image](https://github.com/znichola/ft_transcendence/assets/12100623/f5f8ecd9-5c28-48eb-ad74-f720cac156c4)

**Comment by sophiakoulen** [comment]
But does it work for PRIVATE chatrooms?
Because i imagined for Private chatrooms admins can add other users but for other chatrooms you just Join if you want so you add yourself

**Comment by znichola** [comment]
yes it works for private rooms, but the functionality should be the same for all rooms, no need to do special things for everything, it's more work and less intuitive from a UX perspective.

**Comment by sophiakoulen** [comment]
Okay i'll change the rules then.
