### ISSUE TITLE
how to place file in body for avatar post

### ISSUE THREAD

**Issue by znichola** [znichola/ft_transcendence#68]
<img width="723" alt="Screen Shot 2023-10-21 at 2 15 41 PM" src="https://github.com/znichola/ft_transcendence/assets/12100623/f0e7f460-9853-48a7-a1fa-5588a4a4a23f">

the post function looks like this, tell me what shape the body should have

```ts
export const postUserAvatar = async (login42: string, file: File) => {
  const formData = new FormData();
  formData.append("selectedFile", file);
  return authApi
    .post<HttpStatusCode>(`/user/${login42}/avatar`, formData, {
      headers: {
        "Content-Type": "multipart/form-data",
      },
    })
    .then((r) => r.data);
};

```

**Comment by sophiakoulen** [comment]
Are u getting the error with swagger or with the frontend?
I think the body is multipart/form-data containing the image.

**Comment by znichola** [comment]
impossible to upload an image with swagger, so it's with my frontend code

**Comment by sophiakoulen** [comment]
Okay but are u getting the same error as in swagger or something else?

**Comment by sophiakoulen** [comment]
Okay i managed to change my avatar with Hoppscotch.
The name of the field has to be 'file'.

**Comment by sophiakoulen** [comment]
So try something like:
```
export const postUserAvatar = async (login42: string, file: File) => {
  const formData = new FormData();
  formData.append("file", file);
  return authApi
    .post<HttpStatusCode>(`/user/${login42}/avatar`, formData, {
      headers: {
        "Content-Type": "multipart/form-data",
      },
    })
    .then((r) => r.data);
};
```
