### ISSUE TITLE
conversation api delete

### ISSUE THREAD

**Issue by znichola** [znichola/ft_transcendence#8]
<img width="730" alt="Screen Shot 2023-10-05 at 7 23 54 PM" src="https://github.com/znichola/ft_transcendence_test/assets/12100623/29adb573-f75b-4a30-a1ef-5a124926863d">

add the possibility to delete a conversation for either participant:

`delte on /conversations/{user1}/{user2}`

**Comment by sophiakoulen** [comment]
It's done!
Relevant commit hash: 3745a123e333f3b493583cfef4c1f2d33d054a5c

**Comment by znichola** [comment]
awesome! then, all that's left to do is connect the endpoint to the button!
