### ISSUE TITLE
Not seeing friend request

### ISSUE THREAD

**Issue by sophiakoulen** [znichola/ft_transcendence#83]
I log in as skoulen, send a friend request to Brisa9.
Then i log in as Brisa9, and i don't see any friend request from skoulen anywhere.

**Comment by znichola** [comment]
are you sure? I can't reproduce on my end. 

The friend request is showing up under the friends list, you need to refresh as the websocket is not connected / no setup to send a notification.

**Comment by BPhilagor** [comment]
Je ferme l'issue, on la réouvre si le problème apparait de nouveau
