### ISSUE TITLE
Setting TFA up spam success message

### ISSUE THREAD

**Issue by BPhilagor** [znichola/ft_transcendence#89]

**Comment by BPhilagor** [comment]
State displayed is also wrong

**Comment by Scelewyn** [comment]
Don't know why I'm assigned on this ?
Setting up 2fa correctly generates a secret code and enables tfa for the user in the database

spam success message is frontend related

**Comment by Scelewyn** [comment]
Also after enabling 2fa the popup window should close, if we close it manually it goes back to off while being enabled in the database

**Comment by znichola** [comment]
@BPhilagor can you debug this? Phone is broken, idk how to test tfa without an app like google authenticator.
